// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9keqKf6zWXvDCQL8ldL-LsuESIFoBzaU',
    appId: '1:745317325839:web:2da7a6eef048cdf3b1577a',
    messagingSenderId: '745317325839',
    projectId: 'sih-temp-157df',
    authDomain: 'sih-temp-157df.firebaseapp.com',
    databaseURL: 'https://sih-temp-157df-default-rtdb.firebaseio.com',
    storageBucket: 'sih-temp-157df.firebasestorage.app',
    measurementId: 'G-30L5ZC9HXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpShgQZlGwpT7iRo1ChpZ4m9fLA1sD3ls',
    appId: '1:745317325839:android:8d2882e23ac8e2f1b1577a',
    messagingSenderId: '745317325839',
    projectId: 'sih-temp-157df',
    databaseURL: 'https://sih-temp-157df-default-rtdb.firebaseio.com',
    storageBucket: 'sih-temp-157df.firebasestorage.app',
  );
}
